--- #YAML:1.0
name:                Catalyst-Plugin-FillInForm
version:             0.07
abstract:            ~
license:             ~
author:              
    - Sebastian Riedel (sri@oook.de)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst:                      2.99
    HTML::FillInForm:              0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
